//              LISTAS ENLAZADAS
/*
UNA LISTA ENLAZADA CONSTA DE UN NÚMERO DE NODOS CON DOS COMPONENTES
(CAMPOS), UN ENLACE AL SIGUIENTE NODO DE LA LISTA Y UN VALOR, QUE 
PUEDE SER DE CUALQUIER TIPO.
*/
//              CLASIFICACION DE LISTAS ENLAZADAS
/*
LAS LISTAS SE PUEDEN DIVIDIR EN CUATRO CATEGORIAS: 
1- LISTAS SIMPLEMENTE ENLAZADA
2- LISTA DOBLEMENTE ENLAZADA
3- LISTA CIRCULAR SIMPLEMENTE ENLAZADA
4- LISTA CIRCULAR DOBLEMENTE ENLAZADA
*/
//              1 LISTA SIMPLEMENTE ENLAZADA
/*
CADA NODO(ELEMENTO) CONTIENE UN UNICO ENLACE QUE CONECTA ESE NODO AL
NODO SIGUIENTE O NODO SUCESOR. LA LISTA ES EFECIENTE EN RECORRIDOS 
DIRECTOS
*/